### ISSUE TITLE
File missing in data folder

### ISSUE THREAD

**Issue by Douglas2Code** [LysSanzMoreta/DRAUPNIR_ASR#1]
Hey, I am trying to run the code, but it seems that there is a file missing from the data folder which causes the following error:

FileNotFoundError: [Errno 2] File /home/DRAUPNIR_ASR/draupnir/src/draupnir/data/AA_properties.txt does not exist: '/home/esbg/DRAUPNIR_ASR/draupnir/src/draupnir/data/AA_properties.txt'

The error seems pointing towards https://github.com/LysSanzMoreta/DRAUPNIR_ASR/blob/f4638a2df8acaec9e9e73e34cadbf60a8ec065d0/draupnir/src/draupnir/utils.py#L57

**Comment by LysSanzMoreta** [comment]
@Douglas2Code  You are right. It is an easy fix. Let me get back to you.

**Comment by LysSanzMoreta** [comment]
@Douglas2Code  I have added the missing files. Hopefully, that will do.

**Comment by LysSanzMoreta** [comment]
Hi! I close this issue, feel free to re-open it if something is still missing :)
